/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 09 05:57:57 GMT 2024
 */

package br.com.swconsultoria.nfe.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import br.com.swconsultoria.nfe.dom.ConfiguracoesNfe;
import br.com.swconsultoria.nfe.util.ConfiguracoesUtil;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ConfiguracoesUtil_ESTest extends ConfiguracoesUtil_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      try { 
        ConfiguracoesUtil.iniciaConfiguracoes((ConfiguracoesNfe) null, (String) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Configura\u00E7\u00F5es n\u00E3o foram criadas
         //
         verifyException("br.com.swconsultoria.nfe.util.ConfiguracoesUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ConfiguracoesNfe configuracoesNfe0 = new ConfiguracoesNfe();
      // Undeclared exception!
      try { 
        ConfiguracoesUtil.iniciaConfiguracoes(configuracoesNfe0, "Quzs3fr&[HWa1SqeL");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("br.com.swconsultoria.nfe.util.ConfiguracoesUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ConfiguracoesNfe configuracoesNfe0 = new ConfiguracoesNfe();
      // Undeclared exception!
      try { 
        ConfiguracoesUtil.iniciaConfiguracoes(configuracoesNfe0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("br.com.swconsultoria.nfe.util.ConfiguracoesUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ConfiguracoesUtil configuracoesUtil0 = new ConfiguracoesUtil();
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      try { 
        ConfiguracoesUtil.iniciaConfiguracoes((ConfiguracoesNfe) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Configura\u00E7\u00F5es n\u00E3o foram criadas
         //
         verifyException("br.com.swconsultoria.nfe.util.ConfiguracoesUtil", e);
      }
  }
}
